#!/bin/bash
start_g3() {
  # g3 session
  gcert
  SESSION_NAME="google3"
  tmux new-window -n ${SESSION_NAME}
  tmux send-keys "g4d webapk" C-m
  tmux send-keys "cd googleclient/chrome/webapk/" C-m
  tmux new-window -n "server"
  tmux send-keys "g4d webapk" C-m
  tmux send-keys "server" C-m
  tmux split-window -h
  tmux send-keys "cd WebAPK" C-m
}

start_chromium() {
  tmux new -d
  # chromium session
  SESSION_NAME="chromium"
  #1.git/vim
  tmux rename-window ${SESSION_NAME}
  tmux send-keys "cd ${SESSION_NAME}/src" C-m
  tmux send-keys "goma_ctl ensure_start" C-m

  #2.vim
  if [ $# -ne 0 ]
  then
    tmux split-window -h
    tmux send-keys "cd ${SESSION_NAME}/src" C-m
  fi

  tmux new-window
  tmux send-keys "cd ${SESSION_NAME}/src" C-m

  #3.compile
  tmux new-window
  tmux send-keys "cd ${SESSION_NAME}/src" C-m
  #tmux send-keys "autoninja -C out/Debug chrome && out/Debug/chrome"
  tmux send-keys "autoninja -C out/Android/ monochrome_apk"

  ## #4.Layouttest
  ## tmux new-window
  ## tmux send-keys "cd ${SESSION_NAME}/src" C-m
  ## tmux send-keys "cd third_party/blink/tools/" C-m
  ## tmux send-keys "./run_web_tests.py --debug "
}

start_clankium() {
  # clankium session
  SESSION_NAME="clankium"
  # tmux new -d -s ${SESSION_NAME}
  tmux new-window -n ${SESSION_NAME}
  #1.git/vim
  tmux send-keys "cd ${SESSION_NAME}/src" C-m
  #2.vim
  if [ $# -ne 0 ]
  then
    tmux split-window -h
    tmux send-keys "cd ${SESSION_NAME}/src" C-m
  else
    tmux new-window
    tmux send-keys "cd ${SESSION_NAME}/src" C-m
  fi

  #3.compile
  tmux new-window
  tmux send-keys "cd ${SESSION_NAME}/src" C-m
  tmux send-keys "autoninja -C out/Android/ monochrome_apk"
}

start_eirage_common_session() {
  #eirage session
  SESSION_NAME="eirage"
  tmux new-window -n ${SESSION_NAME}
  tmux send-keys "cd eirage.github.io" C-m
}

start_chromium $1
#start_g3
start_clankium $1
start_eirage_common_session

tmux select-window -t 0
tmux select-pane -t 0

tmux a
#end
