#!/bin/bash

prodaccess

tmux new -d


# chromium session
SESSION_NAME="chromium"
# tmux new -d -s ${SESSION_NAME}
#1.git/vim
tmux rename-window ${SESSION_NAME}
tmux send-keys "cd ${SESSION_NAME}/src" C-m
tmux send-keys "~/goma/goma_ctl.py ensure_start" C-m
tmux split-window -h
tmux send-keys "cd ${SESSION_NAME}/src" C-m
## #2.vim
## tmux new-window
## tmux send-keys "cd ${SESSION_NAME}/src" C-m
## tmux split-window -h
## tmux send-keys "cd ${SESSION_NAME}/src" C-m
#3.compile
tmux new-window
tmux send-keys "cd ${SESSION_NAME}/src" C-m
#tmux send-keys "autoninja -C out/Debug chrome && out/Debug/chrome"
tmux send-keys "autoninja -C out/Android/ chrome_apk"
## #4.Layouttest
## tmux new-window
## tmux send-keys "cd ${SESSION_NAME}/src" C-m
## tmux send-keys "cd third_party/blink/tools/" C-m
## tmux send-keys "./run_web_tests.py --debug "

#g3 session
SESSION_NAME="google3"
tmux new-window -n ${SESSION_NAME}
tmux send-keys "g4d webapk" C-m
#tmux send-keys "cd googleclient/chrome/webapk/" C-m
tmux new-window -n "server"
tmux send-keys "g4d webapk" C-m
tmux send-keys "blaze run //googleclient/chrome/webapk:webapk_server -- -alsologtostderr -bigtable=/bigtable/srv-iy/chrome-webapk.webapks-test -minimum_shell_update_version=5" C-m
tmux split-window -h
tmux send-keys "cd WebAPK" C-m

## #WebAPK folder
## SESSION_NAME="WebAPK"
## tmux new-window -n ${SESSION_NAME}
## tmux send-keys "cd WebAPK" C-m

# clankium session
SESSION_NAME="clankium"
# tmux new -d -s ${SESSION_NAME}
tmux new-window -n ${SESSION_NAME}
#1.git/vim
tmux send-keys "cd ${SESSION_NAME}/src" C-m
tmux split-window -h
tmux send-keys "cd ${SESSION_NAME}/src" C-m
#2.compile
tmux new-window
tmux send-keys "cd ${SESSION_NAME}/src" C-m
tmux send-keys "autoninja -C out/Android/ chrome_public_apk"
## #3.Layouttest
## tmux new-window
## tmux send-keys "cd ${SESSION_NAME}/src" C-m
## tmux send-keys "cd third_party/blink/tools/" C-m
## tmux send-keys "./run_web_tests.py --debug "

#eirage session
SESSION_NAME="eirage"
# tmux new -d -s ${SESSION_NAME}
tmux new-window -n ${SESSION_NAME}
tmux send-keys "cd eirage.github.io" C-m

tmux select-window -t 0
tmux select-pane -t 0

tmux a
#end
